name: PvPWager
version: '1.0.0'
main: de.zfzfg.pvpwager.PvPWager
api-version: '1.20'
author: zfzfg
description: Advanced PvP Wager System with GUI and Arenas
softdepend: [Vault, Multiverse-Core, Multiverse-Inventories]

commands:
  pvp:
    description: Hauptbefehl für PvP-Wager System
    usage: |
      /pvp accept <spieler> - Akzeptiere Anfrage
      /pvp deny <spieler> - Lehne Anfrage ab
      /pvp spectate <spieler> - Schaue Match zu
      /pvp leave - Verlasse Zuschauer-Modus
    aliases: [duel, fight]
  
  pvpa:
    description: Sende PvP-Anfrage an einen Spieler
    usage: /pvpa <spieler>
  
  surrender:
    description: Gebe das Match auf
    usage: /surrender confirm
  
  draw:
    description: Stimme für Unentschieden
    usage: /draw accept

permissions:
  pvpwager.use:
    description: Erlaubt die Nutzung des PvP-Systems
    default: true
  
  pvpwager.spectate:
    description: Erlaubt das Zuschauen bei Matches
    default: true
  
  pvpwager.spectate.all:
    description: Erlaubt das Zuschauen bei allen Matches
    default: op
  
  pvpwager.bypass.betlimit:
    description: Umgeht Wetteinsatz-Limits
    default: op
  
  pvpwager.admin:
    description: Alle Admin-Rechte
    default: op
    children:
      pvpwager.spectate.all: true
      pvpwager.bypass.betlimit: true